"""
execution/ctrader_client.py
----------------------------
IC Markets / cTrader Open API client for IATIS (v4 — corrected).

Protocol : TCP with Protobuf messages (NOT REST)
Library  : ctrader-open-api 0.9.2+

WHAT CHANGED vs v3 (all fixes verified against the real protobuf schema
generated by `ctrader-open-api`):

  CRITICAL
    C1. place_market_order() no longer reads a non-existent
        `CTraderOrder.entry_price`. It sends ABSOLUTE stopLoss / takeProfit
        (ProtoOANewOrderReq.stopLoss / .takeProfit are doubles), so no entry
        reference is required for a market order.
    C2. Execution response is parsed correctly. The reply to
        ProtoOANewOrderReq is a ProtoOAExecutionEvent whose ids/prices live
        under .deal / .position / .order — NOT at the top level. executionPrice
        is a real price and is NOT divided by 100_000.
    C3. Order volume is converted from lots to the API's volume unit using the
        symbol's real `lotSize` (fetched via ProtoOASymbolByIdReq), then snapped
        to stepVolume and clamped to [minVolume, maxVolume]. Passing "centi-lots"
        directly (the old bug) sent a near-zero volume that the broker rejects.

  MAJOR
    M1. READY-state race fixed: whichever of {trader info, symbols list} arrives
        last triggers the READY transition via _maybe_ready().
    M2. Account info uses fields that actually exist on ProtoOATrader
        (balance + moneyDigits, leverageInCents). Non-existent fields
        (depositAsset.name, marginUsed, freeMargin) are no longer referenced.
    M3. Position tracking is populated from ProtoOAExecutionEvent (the real
        source of position lifecycle) instead of dead PositionOpen/Close handlers.

  MINOR
    - Removed unused imports; added a lock around shared state; set both
      `label` and `comment`; documented single-reactor-per-process behaviour.

Connection state flow:
  DISCONNECTED → TCP_CONNECTED → APP_AUTH_OK → ACCOUNT_AUTH_OK
              → SYMBOLS_LOADED → READY
"""
from __future__ import annotations

import os
import threading
import time
from dataclasses import dataclass, field
from enum import Enum
from queue import Queue
from typing import Any

from utils.logger import get_logger

logger = get_logger(__name__)


# ─── Connection State Machine ──────────────────────────────────────────────

class ConnectionState(Enum):
    DISCONNECTED = "DISCONNECTED"
    TCP_CONNECTED = "TCP_CONNECTED"
    APP_AUTH_OK = "APP_AUTH_OK"
    ACCOUNT_AUTH_OK = "ACCOUNT_AUTH_OK"
    SYMBOLS_LOADED = "SYMBOLS_LOADED"
    READY = "READY"
    ERROR = "ERROR"


# ─── Symbol mapping ────────────────────────────────────────────────────────

IATIS_TO_CTRADER: dict[str, str] = {
    # FX Majors
    "EURUSD": "EURUSD",   "GBPUSD": "GBPUSD",   "USDJPY": "USDJPY",
    "USDCHF": "USDCHF",   "AUDUSD": "AUDUSD",   "USDCAD": "USDCAD",
    "NZDUSD": "NZDUSD",
    # FX Crosses
    "EURJPY": "EURJPY",   "GBPJPY": "GBPJPY",   "AUDJPY": "AUDJPY",
    "EURGBP": "EURGBP",   "EURCHF": "EURCHF",
    # Metals
    "XAUUSD": "XAUUSD",   "XAGUSD": "XAGUSD",
    # Energy
    "USOIL":  "XTIUSD",
    # Indices
    "US30":   "DJ30",     "NAS100": "NAS100",    "SPX500": "SP500",
    # Crypto
    "BTCUSD": "BTCUSD",   "ETHUSD": "ETHUSD",
}

CTRADER_TO_IATIS = {v: k for k, v in IATIS_TO_CTRADER.items()}

RECOMMENDED_LEVERAGE = {
    "forex":  50,
    "metal":  20,
    "energy": 20,
    "index":  20,
    "crypto": 10,
}

ASSET_CLASS = {
    **{s: "forex" for s in ["EURUSD", "GBPUSD", "USDJPY", "USDCHF", "AUDUSD",
                            "USDCAD", "NZDUSD", "EURJPY", "GBPJPY", "AUDJPY",
                            "EURGBP", "EURCHF"]},
    "XAUUSD": "metal",  "XAGUSD": "metal",
    "USOIL":  "energy",
    "US30":   "index",  "NAS100": "index",  "SPX500": "index",
    "BTCUSD": "crypto", "ETHUSD": "crypto",
}

# Last-resort contract sizes, expressed in the cTrader `volume` unit (1/100 of
# the base-asset unit) that corresponds to 1.00 lot. These are BROKER-SPECIFIC
# and are used ONLY when the live symbol details could not be fetched. The
# authoritative value is always the `lotSize` returned by ProtoOASymbolByIdRes.
_FALLBACK_LOT_SIZE: dict[str, int] = {
    "XAUUSD": 10_000,    # 100 oz
    "XAGUSD": 500_000,   # 5000 oz
    "USOIL":  100_000,   # 1000 barrels (XTIUSD)
    "US30":   100,       # index — VERIFY against broker contract spec
    "NAS100": 100,       # index — VERIFY against broker contract spec
    "SPX500": 100,       # index — VERIFY against broker contract spec
    "BTCUSD": 100,       # 1 BTC
    "ETHUSD": 100,       # 1 ETH
}
_DEFAULT_FOREX_LOT_SIZE = 10_000_000  # 1 lot = 100_000 units


def _fallback_lot_size(iatis_symbol: str) -> int:
    """Return a best-effort lotSize when live symbol details are unavailable."""
    return _FALLBACK_LOT_SIZE.get(iatis_symbol, _DEFAULT_FOREX_LOT_SIZE)


# ─── Data classes ─────────────────────────────────────────────────────────

@dataclass
class CTraderOrder:
    """A market order request.

    stop_loss / take_profit are ABSOLUTE prices (the levels produced by the
    IATIS pipeline). entry_price is optional and kept only for reference /
    logging — the broker fills a market order at its own price.
    """
    symbol: str
    direction: str            # "BUY" or "SELL"
    volume: int               # centi-lots (0.01-lot units), from calculate_volume()
    stop_loss: float
    take_profit: float
    comment: str = "IATIS"
    entry_price: float = 0.0  # optional signal reference price


@dataclass
class CTraderResult:
    success: bool
    order_id: str = ""
    position_id: str = ""
    symbol: str = ""
    direction: str = ""
    volume: int = 0
    entry_price: float = 0.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    error: str = ""
    raw: dict = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "success": self.success,
            "order_id": self.order_id,
            "position_id": self.position_id,
            "symbol": self.symbol,
            "direction": self.direction,
            "volume": self.volume,
            "entry_price": self.entry_price,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
            "error": self.error,
        }


@dataclass
class AccountInfo:
    account_id: int
    balance: float
    equity: float
    margin_used: float
    margin_free: float
    currency: str
    leverage: int


@dataclass
class OpenPosition:
    position_id: str
    symbol: str
    direction: str
    volume: int
    entry_price: float
    current_price: float
    unrealized_pnl: float
    stop_loss: float
    take_profit: float


@dataclass
class _SymbolDetails:
    """Trading spec fetched via ProtoOASymbolByIdRes (all volumes in API units)."""
    symbol_id: int
    digits: int
    pip_position: int
    lot_size: int
    min_volume: int
    step_volume: int
    max_volume: int


# ─── cTrader Client (v4 — corrected) ───────────────────────────────────────

class CTraderClient:
    """IC Markets cTrader Open API client.

    Thread model: a single Twisted reactor runs in a background daemon thread
    for the whole process. All protobuf sends are marshalled onto the reactor
    thread via reactor.callFromThread; results are handed back to the calling
    (synchronous) thread via threading.Event.
    """

    DEMO_HOST = "demo.ctraderapi.com"
    LIVE_HOST = "live.ctraderapi.com"
    PORT = 5035

    # Response wait budgets (seconds)
    ORDER_TIMEOUT = 15.0
    AUTH_TIMEOUT = 15.0        # app/account auth round-trips
    BOOTSTRAP_TIMEOUT = 20.0   # trader info / symbols list / symbol details

    def __init__(
        self,
        client_id: str | None = None,
        client_secret: str | None = None,
        account_id: int | None = None,
        access_token: str | None = None,
        environment: str | None = None,
    ) -> None:
        self.client_id = client_id or os.environ.get("CTRADER_CLIENT_ID", "")
        self.client_secret = client_secret or os.environ.get("CTRADER_CLIENT_SECRET", "")
        self.account_id = int(account_id or os.environ.get("CTRADER_ACCOUNT_ID", 0))
        self.access_token = access_token or os.environ.get("CTRADER_ACCESS_TOKEN", "")
        env = environment or os.environ.get("CTRADER_ENVIRONMENT", "demo")
        self.host = self.DEMO_HOST if env == "demo" else self.LIVE_HOST
        self.environment = env

        self._client: Any = None
        self._state = ConnectionState.DISCONNECTED
        self._reactor_running = False

        # Guards shared state touched by both the reactor thread and callers.
        self._lock = threading.RLock()

        # Symbol mappings.
        self._symbol_name_to_id: dict[str, int] = {}
        self._symbol_id_to_name: dict[int, str] = {}
        self._symbol_details: dict[int, _SymbolDetails] = {}

        # Account / positions.
        self._account_info: AccountInfo | None = None
        self._positions: dict[str, OpenPosition] = {}

        # Async → sync bridge for account info.
        self._message_queue: Queue = Queue()
        self._result_event = threading.Event()

        self._validate_credentials()

    # ─── Credentials ───────────────────────────────────────────────────────

    def _validate_credentials(self) -> None:
        missing = []
        if not self.client_id:
            missing.append("CTRADER_CLIENT_ID")
        if not self.client_secret:
            missing.append("CTRADER_CLIENT_SECRET")
        if not self.account_id:
            missing.append("CTRADER_ACCOUNT_ID")
        if not self.access_token:
            missing.append("CTRADER_ACCESS_TOKEN")
        if missing:
            raise ValueError(
                f"Missing cTrader credentials: {', '.join(missing)}\n"
                f"See execution/ctrader_client.py docstring for setup instructions."
            )

    # ─── State ──────────────────────────────────────────────────────────────

    def _set_state(self, new_state: ConnectionState) -> None:
        with self._lock:
            old_state = self._state
            self._state = new_state
        logger.info(f"🔄 State transition: {old_state.value} → {new_state.value}")

    def _maybe_ready(self) -> None:
        """Transition to READY once BOTH account info and symbols are loaded.

        FIX M1: either handler may finish last; both must be able to complete
        the connection, otherwise a symbols-before-trader ordering would hang.
        """
        with self._lock:
            if (
                self._account_info is not None
                and self._symbol_name_to_id
                and self._state not in (ConnectionState.READY, ConnectionState.ERROR)
            ):
                should_promote = True
            else:
                should_promote = False
        if should_promote:
            self._set_state(ConnectionState.READY)

    # ─── Auth / bootstrap chain ──────────────────────────────────────────────

    def _on_tcp_connected(self, client: Any) -> None:
        self._set_state(ConnectionState.TCP_CONNECTED)
        logger.info(f"✅ TCP connected to {self.host}:{self.PORT}")
        self._send_app_auth(client)

    def _send_app_auth(self, client: Any) -> None:
        try:
            from ctrader_open_api.messages.OpenApiMessages_pb2 import (
                ProtoOAApplicationAuthReq,
            )

            req = ProtoOAApplicationAuthReq()
            req.clientId = self.client_id
            req.clientSecret = self.client_secret
            logger.debug("📤 Sending: ProtoOAApplicationAuthReq")
            d = client.send(req, responseTimeoutInSeconds=self.AUTH_TIMEOUT)
            d.addCallback(lambda res: self._on_app_auth(client, res))
            d.addErrback(lambda f: self._on_error("app_auth", f))
        except Exception as exc:
            logger.error(f"❌ Failed to send app auth: {exc}")
            self._set_state(ConnectionState.ERROR)

    def _on_app_auth(self, client: Any, response: Any) -> None:
        """Proceed only if the server actually returned an ApplicationAuthRes."""
        if response.__class__.__name__ != "ProtoOAApplicationAuthRes":
            logger.error(
                f"❌ App auth failed — unexpected response "
                f"{response.__class__.__name__} "
                f"(code={getattr(response, 'errorCode', '')} "
                f"{getattr(response, 'description', '')})"
            )
            self._set_state(ConnectionState.ERROR)
            return
        self._set_state(ConnectionState.APP_AUTH_OK)
        logger.info("✅ Application authenticated")
        self._send_account_auth(client)

    def _send_account_auth(self, client: Any) -> None:
        try:
            from ctrader_open_api.messages.OpenApiMessages_pb2 import (
                ProtoOAAccountAuthReq,
            )

            req = ProtoOAAccountAuthReq()
            req.ctidTraderAccountId = self.account_id
            req.accessToken = self.access_token
            logger.debug(f"📤 Sending: ProtoOAAccountAuthReq (account {self.account_id})")
            d = client.send(req, responseTimeoutInSeconds=self.AUTH_TIMEOUT)
            d.addCallback(lambda res: self._on_account_auth(client, res))
            d.addErrback(lambda f: self._on_error("account_auth", f))
        except Exception as exc:
            logger.error(f"❌ Failed to send account auth: {exc}")
            self._set_state(ConnectionState.ERROR)

    def _on_account_auth(self, client: Any, response: Any) -> None:
        """Proceed only if the server actually returned an AccountAuthRes."""
        if response.__class__.__name__ != "ProtoOAAccountAuthRes":
            logger.error(
                f"❌ Account auth failed — unexpected response "
                f"{response.__class__.__name__} "
                f"(code={getattr(response, 'errorCode', '')} "
                f"{getattr(response, 'description', '')})"
            )
            self._set_state(ConnectionState.ERROR)
            return
        self._set_state(ConnectionState.ACCOUNT_AUTH_OK)
        logger.info(f"✅ Account authorized: {self.account_id}")
        self._send_trader_req(client)
        self._send_symbols_list_req(client)

    def _send_trader_req(self, client: Any) -> None:
        try:
            from ctrader_open_api.messages.OpenApiMessages_pb2 import ProtoOATraderReq

            req = ProtoOATraderReq()
            req.ctidTraderAccountId = self.account_id
            logger.debug("📤 Sending: ProtoOATraderReq")
            d = client.send(req, responseTimeoutInSeconds=self.BOOTSTRAP_TIMEOUT)
            d.addErrback(lambda f: self._on_error("trader_req", f))
        except Exception as exc:
            logger.error(f"❌ Failed to send trader req: {exc}")

    def _send_symbols_list_req(self, client: Any) -> None:
        try:
            from ctrader_open_api.messages.OpenApiMessages_pb2 import (
                ProtoOASymbolsListReq,
            )

            req = ProtoOASymbolsListReq()
            req.ctidTraderAccountId = self.account_id
            logger.debug("📤 Sending: ProtoOASymbolsListReq")
            d = client.send(req, responseTimeoutInSeconds=self.BOOTSTRAP_TIMEOUT)
            d.addErrback(lambda f: self._on_error("symbols_list", f))
        except Exception as exc:
            logger.error(f"❌ Failed to send symbols list req: {exc}")

    def _send_symbol_details_req(self, client: Any, symbol_ids: list[int]) -> None:
        """Fetch full trading specs (lotSize/digits/min/step) for mapped symbols.

        Best-effort: READY does not block on this. If it never arrives,
        place_market_order() falls back to _FALLBACK_LOT_SIZE with a warning.
        """
        if not symbol_ids:
            return
        try:
            from ctrader_open_api.messages.OpenApiMessages_pb2 import (
                ProtoOASymbolByIdReq,
            )

            req = ProtoOASymbolByIdReq()
            req.ctidTraderAccountId = self.account_id
            req.symbolId.extend(symbol_ids)
            logger.debug(f"📤 Sending: ProtoOASymbolByIdReq ({len(symbol_ids)} ids)")
            d = client.send(req, responseTimeoutInSeconds=self.BOOTSTRAP_TIMEOUT)
            d.addErrback(lambda f: self._on_error("symbol_details", f))
        except Exception as exc:
            logger.error(f"❌ Failed to send symbol details req: {exc}")

    # ─── Universal message dispatcher ────────────────────────────────────────

    def _on_message(self, client: Any, message: Any) -> None:
        """Route every inbound protobuf message to its handler by type name."""
        msg_type = message.__class__.__name__
        logger.debug(f"📨 Received: {msg_type}")
        try:
            if msg_type == "ProtoOATraderRes":
                self._on_trader_res(message)
            elif msg_type == "ProtoOASymbolsListRes":
                self._on_symbols_list_res(client, message)
            elif msg_type == "ProtoOASymbolByIdRes":
                self._on_symbol_details_res(message)
            elif msg_type == "ProtoOAExecutionEvent":
                self._on_execution_event(message)
            elif msg_type == "ProtoOAErrorRes":
                self._on_error_res(message)
            elif msg_type == "ProtoOAOrderErrorEvent":
                self._on_order_error_event(message)
            elif msg_type in ("ProtoOAApplicationAuthRes", "ProtoOAAccountAuthRes"):
                # Handled by the correlated auth callbacks; nothing to do here.
                logger.debug(f"↩ {msg_type}")
            else:
                code = getattr(message, "errorCode", "")
                extra = (
                    f" errorCode={code} desc={getattr(message, 'description', '')}"
                    if code else ""
                )
                logger.warning(f"⚠️ Unhandled message type: {msg_type}{extra}")
        except Exception as exc:
            logger.error(f"❌ Error in message dispatcher ({msg_type}): {exc}")

    def _on_trader_res(self, message: Any) -> None:
        """Handle ProtoOATraderRes (account info).

        FIX M2: use only fields that exist on ProtoOATrader. `balance` is scaled
        by 10**moneyDigits. Used/free margin are not carried by this message, so
        they are reported as 0.0 (fetch via reconcile if you need them).
        """
        try:
            if not hasattr(message, "trader"):
                logger.error("❌ ProtoOATraderRes has no `trader` field")
                return
            trader = message.trader
            money_digits = int(getattr(trader, "moneyDigits", 2) or 2)
            scale = 10 ** money_digits
            balance = float(trader.balance) / scale
            leverage = int(getattr(trader, "leverageInCents", 0) or 0) // 100

            with self._lock:
                self._account_info = AccountInfo(
                    account_id=int(trader.ctidTraderAccountId),
                    balance=balance,
                    equity=balance,          # equity ≈ balance without open-PnL feed
                    margin_used=0.0,         # not available from ProtoOATrader
                    margin_free=balance,     # conservative proxy
                    currency=os.environ.get("CTRADER_ACCOUNT_CURRENCY", "USD"),
                    leverage=leverage,
                )
            logger.info(
                f"💰 Account info: balance={balance:.2f} "
                f"{self._account_info.currency}, leverage=1:{leverage}"
            )
            self._result_event.set()
            self._maybe_ready()
        except Exception as exc:
            logger.error(f"❌ Error processing ProtoOATraderRes: {exc}")

    def _on_symbols_list_res(self, client: Any, message: Any) -> None:
        """Handle ProtoOASymbolsListRes (light symbol list: name ↔ id)."""
        try:
            symbols = getattr(message, "symbol", None)
            if not symbols:
                logger.warning("⚠️ ProtoOASymbolsListRes contained no symbols")
                return

            wanted_ids: list[int] = []
            with self._lock:
                for sym in symbols:
                    self._symbol_name_to_id[sym.symbolName] = sym.symbolId
                    self._symbol_id_to_name[sym.symbolId] = sym.symbolName

                missing = [
                    ct for ct in IATIS_TO_CTRADER.values()
                    if ct not in self._symbol_name_to_id
                ]
                wanted_ids = [
                    self._symbol_name_to_id[ct]
                    for ct in IATIS_TO_CTRADER.values()
                    if ct in self._symbol_name_to_id
                ]

            logger.info(f"📊 Loaded {len(self._symbol_name_to_id)} symbols")
            if missing:
                logger.warning(f"⚠️ IATIS symbols missing on broker: {missing[:5]}...")
            else:
                logger.info("✅ All IATIS symbols available")

            self._set_state(ConnectionState.SYMBOLS_LOADED)
            # Kick off best-effort details fetch (needed for correct volumes).
            self._send_symbol_details_req(client, wanted_ids)
            self._maybe_ready()
        except Exception as exc:
            logger.error(f"❌ Error processing ProtoOASymbolsListRes: {exc}")

    def _on_symbol_details_res(self, message: Any) -> None:
        """Handle ProtoOASymbolByIdRes (full specs incl. lotSize/min/step)."""
        try:
            symbols = getattr(message, "symbol", None)
            if not symbols:
                return
            with self._lock:
                for sym in symbols:
                    self._symbol_details[sym.symbolId] = _SymbolDetails(
                        symbol_id=int(sym.symbolId),
                        digits=int(getattr(sym, "digits", 5)),
                        pip_position=int(getattr(sym, "pipPosition", 4)),
                        lot_size=int(getattr(sym, "lotSize", 0) or 0),
                        min_volume=int(getattr(sym, "minVolume", 0) or 0),
                        step_volume=int(getattr(sym, "stepVolume", 0) or 0),
                        max_volume=int(getattr(sym, "maxVolume", 0) or 0),
                    )
            logger.info(f"🧾 Loaded trading specs for {len(symbols)} symbol(s)")
        except Exception as exc:
            logger.error(f"❌ Error processing ProtoOASymbolByIdRes: {exc}")

    def _on_execution_event(self, message: Any) -> None:
        """Handle ProtoOAExecutionEvent and maintain the open-position map.

        FIX M3: this is the real source of position lifecycle events; the old
        PositionOpen/Close handlers referenced message types that the server
        never sends.
        """
        try:
            exec_type = getattr(message, "executionType", None)
            logger.debug(f"📊 Execution event: type={exec_type}")

            position = getattr(message, "position", None)
            if not position or not getattr(position, "positionId", 0):
                return

            trade_data = getattr(position, "tradeData", None)
            sym_id = int(getattr(trade_data, "symbolId", 0)) if trade_data else 0
            ct_name = self._symbol_id_to_name.get(sym_id, "")
            iatis_symbol = CTRADER_TO_IATIS.get(ct_name, ct_name)

            status = getattr(position, "positionStatus", None)
            with self._lock:
                # 2 == POSITION_STATUS_CLOSED
                if status == 2:
                    self._positions.pop(iatis_symbol, None)
                    logger.info(f"📉 Position closed: {iatis_symbol}")
                else:
                    side = getattr(trade_data, "tradeSide", None) if trade_data else None
                    self._positions[iatis_symbol] = OpenPosition(
                        position_id=str(position.positionId),
                        symbol=iatis_symbol,
                        direction="BUY" if side == 1 else "SELL",
                        volume=int(getattr(trade_data, "volume", 0)) if trade_data else 0,
                        entry_price=float(getattr(position, "price", 0.0)),
                        current_price=float(getattr(position, "price", 0.0)),
                        unrealized_pnl=0.0,
                        stop_loss=float(getattr(position, "stopLoss", 0.0)),
                        take_profit=float(getattr(position, "takeProfit", 0.0)),
                    )
                    logger.info(f"📈 Position tracked: {iatis_symbol}")
        except Exception as exc:
            logger.error(f"❌ Error processing ProtoOAExecutionEvent: {exc}")

    def _on_order_error_event(self, message: Any) -> None:
        code = getattr(message, "errorCode", "")
        desc = getattr(message, "description", "")
        logger.error(f"❌ Order error event: {code} — {desc}")

    def _on_error_res(self, message: Any) -> None:
        """Handle ProtoOAErrorRes: surface the server's reason and fail fast.

        This is the message the server returns when app/account auth, the trader
        request, or the symbols request is rejected. Previously it was swallowed
        at DEBUG, so a rejected bootstrap looked like a blind connect timeout.
        """
        code = getattr(message, "errorCode", "")
        desc = getattr(message, "description", "")
        logger.error(f"❌ Server error (ProtoOAErrorRes): {code} — {desc}")
        self._set_state(ConnectionState.ERROR)

    def _on_disconnect(self, client: Any, reason: Any) -> None:
        self._set_state(ConnectionState.DISCONNECTED)
        logger.warning(f"⚠️ Disconnected: {reason}")

    def _on_error(self, context: str, failure: Any) -> None:
        error_msg = (
            failure.getErrorMessage() if hasattr(failure, "getErrorMessage")
            else str(failure)
        )
        logger.error(f"❌ Protocol error ({context}): {error_msg}")
        self._set_state(ConnectionState.ERROR)

    # ─── Connection ──────────────────────────────────────────────────────────

    def connect(self, timeout: float = 30.0) -> bool:
        """Establish an authenticated, READY connection to the cTrader API."""
        try:
            from ctrader_open_api import Client, TcpProtocol
            from twisted.internet import reactor

            client = Client(self.host, self.PORT, TcpProtocol)
            self._client = client

            # Register ALL callbacks BEFORE starting the service.
            # NOTE: ctrader-open-api's Client exposes only these three setters.
            # There is no setErrorCallback — transport errors surface via the
            # disconnected callback and via each send()'s Deferred errback.
            client.setConnectedCallback(self._on_tcp_connected)
            client.setMessageReceivedCallback(self._on_message)
            client.setDisconnectedCallback(self._on_disconnect)

            connected = threading.Event()
            error_holder: list[str | None] = [None]
            start_time = time.time()

            def check_status() -> None:
                elapsed = time.time() - start_time
                if self._state == ConnectionState.READY:
                    logger.debug(f"✓ Reached READY in {elapsed:.1f}s")
                    connected.set()
                elif self._state == ConnectionState.ERROR:
                    error_holder[0] = "Connection failed (ERROR state)"
                    connected.set()
                elif elapsed > timeout:
                    error_holder[0] = (
                        f"Connection timeout after {timeout}s. "
                        f"State: {self._state.value}"
                    )
                    connected.set()
                else:
                    reactor.callLater(0.5, check_status)

            if not reactor.running:
                self._reactor_running = True
                logger.debug("🚀 Starting Twisted reactor in background thread...")
                t = threading.Thread(
                    target=reactor.run,
                    kwargs={"installSignalHandlers": False},
                    daemon=True,
                )
                t.start()
                time.sleep(0.1)

            logger.info(f"🔌 Connecting to {self.host}:{self.PORT}...")
            reactor.callFromThread(client.startService)
            reactor.callFromThread(check_status)

            connected.wait(timeout=timeout + 2)

            if error_holder[0]:
                logger.error(f"❌ Connection error: {error_holder[0]}")
                return False

            if self._state == ConnectionState.READY:
                logger.info(
                    f"🟢 cTrader READY | env={self.environment} "
                    f"account={self.account_id} "
                    f"symbols={len(self._symbol_name_to_id)} "
                    f"balance={self._account_info.balance if self._account_info else 'N/A'}"
                )
                return True

            logger.error(f"❌ Connection incomplete. State: {self._state.value}")
            return False

        except Exception as exc:
            logger.error(f"❌ Connect failed: {exc}", exc_info=True)
            return False

    # ─── Account ─────────────────────────────────────────────────────────────

    def get_account_info(self) -> AccountInfo | None:
        """Return the cached account info (populated during connect())."""
        if self._state != ConnectionState.READY:
            logger.error(f"❌ Not ready to fetch account info. State: {self._state.value}")
            return None
        with self._lock:
            info = self._account_info
        if info:
            logger.debug(f"✅ Account info (cached): {info.balance} {info.currency}")
            return info
        logger.error("❌ Account info not available")
        return None

    # ─── Volume ──────────────────────────────────────────────────────────────

    def calculate_volume(
        self,
        symbol: str,
        balance: float,
        risk_pct: float,
        sl_distance_price: float,
        leverage: int | None = None,
    ) -> int:
        """Position size in centi-lots (0.01-lot units).

        The result is later converted to the broker's native `volume` unit in
        place_market_order() using the symbol's real lotSize.
        """
        ac = ASSET_CLASS.get(symbol, "forex")
        risk_usd = balance * risk_pct

        if ac == "forex":
            pip_size = 0.01 if "JPY" in symbol else 0.0001
            sl_pips = sl_distance_price / pip_size
            pip_value_per_lot = 10.0
        elif ac == "metal":
            if symbol == "XAUUSD":
                pip_size = 0.01
                sl_pips = sl_distance_price / pip_size
                pip_value_per_lot = 1.0
            else:
                pip_size = 0.001
                sl_pips = sl_distance_price / pip_size
                pip_value_per_lot = 0.5
        elif ac in ("energy", "index", "crypto"):
            sl_pips = sl_distance_price
            pip_value_per_lot = 1.0
        else:
            sl_pips = sl_distance_price / 0.0001
            pip_value_per_lot = 10.0

        if sl_pips <= 0:
            logger.warning(f"⚠️ Invalid SL distance for {symbol}: {sl_distance_price}")
            return 0

        lots = risk_usd / (sl_pips * pip_value_per_lot)
        centi_lots = max(1, min(int(lots * 100), 10_000))  # 0.01 .. 100 lots
        return centi_lots

    def _to_api_volume(self, iatis_symbol: str, ct_symbol: str, centi_lots: int) -> int:
        """Convert centi-lots → broker `volume` unit using live lotSize.

        FIX C3. Falls back to _FALLBACK_LOT_SIZE (with a warning) if details are
        not loaded, and snaps to stepVolume / clamps to [minVolume, maxVolume]
        when those are known.
        """
        lots = centi_lots / 100.0
        symbol_id = self._symbol_name_to_id.get(ct_symbol)
        details = self._symbol_details.get(symbol_id) if symbol_id is not None else None

        if details and details.lot_size > 0:
            lot_size = details.lot_size
        else:
            lot_size = _fallback_lot_size(iatis_symbol)
            logger.warning(
                f"⚠️ Using FALLBACK lotSize={lot_size} for {iatis_symbol} "
                f"(live symbol details unavailable). Verify before live trading."
            )

        volume = int(round(lots * lot_size))

        if details:
            if details.max_volume > 0:
                volume = min(volume, details.max_volume)
            if details.step_volume > 0:
                volume = (volume // details.step_volume) * details.step_volume
            if details.min_volume > 0:
                volume = max(volume, details.min_volume)

        return max(0, volume)

    # ─── Orders ──────────────────────────────────────────────────────────────

    def place_market_order(self, order: CTraderOrder) -> CTraderResult:
        """Place a market order with absolute SL/TP prices."""
        if self._state != ConnectionState.READY:
            return CTraderResult(
                success=False, symbol=order.symbol,
                error=f"Not ready. State: {self._state.value}",
            )

        if order.direction not in ("BUY", "SELL"):
            return CTraderResult(
                success=False, symbol=order.symbol,
                error=f"Invalid direction: {order.direction!r}",
            )

        ct_symbol = IATIS_TO_CTRADER.get(order.symbol)
        if not ct_symbol:
            return CTraderResult(
                success=False, symbol=order.symbol,
                error=f"Symbol {order.symbol} not in IATIS_TO_CTRADER mapping.",
            )

        symbol_id = self._symbol_name_to_id.get(ct_symbol)
        if symbol_id is None:
            return CTraderResult(
                success=False, symbol=order.symbol,
                error=f"Symbol {ct_symbol} not in loaded symbol list.",
            )

        api_volume = self._to_api_volume(order.symbol, ct_symbol, order.volume)
        if api_volume <= 0:
            return CTraderResult(
                success=False, symbol=order.symbol,
                error=f"Computed API volume is 0 (centi_lots={order.volume}).",
            )

        try:
            from ctrader_open_api.messages.OpenApiMessages_pb2 import ProtoOANewOrderReq
            from ctrader_open_api.messages.OpenApiModelMessages_pb2 import (
                ProtoOAOrderType, ProtoOATradeSide,
            )
            from twisted.internet import reactor

            result_holder: list[CTraderResult | None] = [None]
            done = threading.Event()

            def send_order() -> None:
                try:
                    req = ProtoOANewOrderReq()
                    req.ctidTraderAccountId = self.account_id
                    req.symbolId = symbol_id
                    req.orderType = ProtoOAOrderType.MARKET
                    req.tradeSide = (
                        ProtoOATradeSide.BUY if order.direction == "BUY"
                        else ProtoOATradeSide.SELL
                    )
                    req.volume = api_volume
                    # FIX C1: absolute SL/TP prices — no entry reference needed.
                    if order.stop_loss > 0:
                        req.stopLoss = float(order.stop_loss)
                    if order.take_profit > 0:
                        req.takeProfit = float(order.take_profit)
                    req.label = "IATIS"
                    req.comment = order.comment[:100]

                    logger.info(
                        f"📤 Order: {order.direction} {ct_symbol} vol={api_volume} "
                        f"SL={order.stop_loss} TP={order.take_profit}"
                    )
                    d = self._client.send(
                        req, responseTimeoutInSeconds=self.ORDER_TIMEOUT
                    )
                    d.addCallback(on_response)
                    d.addErrback(on_error)
                except Exception as exc:
                    logger.error(f"❌ Error building/sending order: {exc}")
                    result_holder[0] = CTraderResult(
                        success=False, symbol=order.symbol, error=str(exc),
                    )
                    done.set()

            def on_response(response: Any) -> None:
                # FIX C2: parse ProtoOAExecutionEvent correctly.
                try:
                    result_holder[0] = self._parse_execution_response(order, response)
                except Exception as exc:
                    logger.error(f"❌ Error parsing order response: {exc}")
                    result_holder[0] = CTraderResult(
                        success=False, symbol=order.symbol, error=str(exc),
                    )
                finally:
                    done.set()

            def on_error(failure: Any) -> None:
                error_msg = (
                    failure.getErrorMessage() if hasattr(failure, "getErrorMessage")
                    else str(failure)
                )
                logger.error(f"❌ Order placement failed: {error_msg}")
                result_holder[0] = CTraderResult(
                    success=False, symbol=order.symbol, error=error_msg,
                )
                done.set()

            reactor.callFromThread(send_order)
            done.wait(timeout=self.ORDER_TIMEOUT)

            if result_holder[0] is not None:
                return result_holder[0]
            return CTraderResult(
                success=False, symbol=order.symbol,
                error=f"Order timed out after {self.ORDER_TIMEOUT}s",
            )

        except Exception as exc:
            logger.error(f"❌ Order placement failed: {exc}", exc_info=True)
            return CTraderResult(success=False, symbol=order.symbol, error=str(exc))

    def _parse_execution_response(self, order: CTraderOrder, response: Any) -> CTraderResult:
        """Turn a ProtoOAExecutionEvent into a CTraderResult.

        Ids and prices live under .deal / .position / .order. executionPrice is a
        real price (NOT scaled). An ORDER_ACCEPTED (not yet filled) event is
        reported as a pending success with whatever ids are present.
        """
        msg_type = response.__class__.__name__
        if msg_type != "ProtoOAExecutionEvent":
            # Some errors come back as ProtoOAOrderErrorEvent / ProtoOAErrorRes.
            err = (
                getattr(response, "errorCode", "")
                or getattr(response, "description", "")
                or f"Unexpected response: {msg_type}"
            )
            return CTraderResult(success=False, symbol=order.symbol, error=str(err))

        error_code = getattr(response, "errorCode", "")
        if error_code:
            return CTraderResult(
                success=False, symbol=order.symbol, error=str(error_code),
            )

        deal = getattr(response, "deal", None)
        position = getattr(response, "position", None)
        order_obj = getattr(response, "order", None)

        position_id = ""
        if position is not None and getattr(position, "positionId", 0):
            position_id = str(position.positionId)
        elif deal is not None and getattr(deal, "positionId", 0):
            position_id = str(deal.positionId)

        order_id = ""
        if order_obj is not None and getattr(order_obj, "orderId", 0):
            order_id = str(order_obj.orderId)
        elif deal is not None and getattr(deal, "orderId", 0):
            order_id = str(deal.orderId)

        exec_price = 0.0
        if deal is not None and getattr(deal, "executionPrice", 0):
            exec_price = float(deal.executionPrice)
        elif order_obj is not None and getattr(order_obj, "executionPrice", 0):
            exec_price = float(order_obj.executionPrice)
        elif order.entry_price:
            exec_price = float(order.entry_price)

        result = CTraderResult(
            success=True,
            order_id=order_id,
            position_id=position_id,
            symbol=order.symbol,
            direction=order.direction,
            volume=order.volume,
            entry_price=exec_price,
            stop_loss=order.stop_loss,
            take_profit=order.take_profit,
            raw={"execution_type": getattr(response, "executionType", None)},
        )
        logger.info(
            f"✅ Order response: pos_id={position_id or 'pending'} "
            f"price={exec_price} type={result.raw['execution_type']}"
        )
        return result

    # ─── Misc ────────────────────────────────────────────────────────────────

    def has_open_position(self, symbol: str) -> bool:
        with self._lock:
            return symbol in self._positions

    def test_connection(self) -> bool:
        """Verify credentials/connectivity without placing any order."""
        try:
            logger.info("🧪 Testing cTrader connection...")
            if not self.connect(timeout=10.0):
                logger.error("❌ Connection test failed")
                return False
            info = self.get_account_info()
            if info:
                logger.info(
                    f"✅ cTrader test PASSED | balance={info.balance} {info.currency} "
                    f"leverage=1:{info.leverage} margin_free={info.margin_free}"
                )
                return True
            logger.error("❌ Could not fetch account info")
            return False
        except Exception as exc:
            logger.error(f"❌ Connection test failed: {exc}")
            return False

    def disconnect(self) -> None:
        """Cleanly stop the client service (the shared reactor keeps running)."""
        if self._client:
            try:
                from twisted.internet import reactor
                if reactor.running:
                    logger.debug("Stopping cTrader client service...")
                    reactor.callFromThread(self._client.stopService)
            except Exception as exc:
                logger.warning(f"Error during disconnect: {exc}")
        self._set_state(ConnectionState.DISCONNECTED)
        logger.info("cTrader disconnected")
