"""
storage/post_trade_incidents.py
----------------------------------
Unified Post-Trade Control / Incident Register.

This module does NOT reconcile positions, compute slippage, or evaluate
kill-switch state — that logic already exists and stays exactly where it
is (execution/reconciliation.py, storage/execution_quality.py, storage/
kill_switch.py, scripts/forward_review.py). This module only turns an
already-computed piece of evidence from one of those subsystems into a
durable, auditable INCIDENT record — the supervisory layer institutional
post-trade operations expects but that no single existing subsystem
provides on its own (each one reports its own narrow slice; nothing
turns "reconciliation says mismatch" + "an order timed out" + "the kill
switch just tripped" into one coherent operational picture).

Deduplication: every incident is keyed by a caller-supplied FINGERPRINT
(a stable string describing the underlying condition, e.g.
"RECON_MISMATCH:EURUSD:BROKER_ONLY"). upsert_incident() looks for an
existing incident with that fingerprint that is NOT already in a
terminal state (RESOLVED/WAIVED); if found, it only bumps last_seen_at
(and refreshes evidence/actual_state) — it never creates a new row for
an already-open occurrence. If the fingerprint's only prior match is
itself terminal, a NEW incident is created: a resolved/waived incident
is immutable history, never silently reopened (see resolve_incident's
own docstring).

State machine: OPEN -> ACKNOWLEDGED -> RESOLVED, or OPEN/ACKNOWLEDGED ->
WAIVED. acknowledge/waive are ONLY ever called from an explicit operator
action (execution/routes/post_trade.py) — never automatically. resolve
is likewise operator-only, with exactly one narrow, evidence-driven
exception: execution/post_trade_monitor.py's scan_reconciliation() may
auto-resolve an OUTCOME_RECONCILIATION_GAP incident when execution/
reconciliation.py's own repair_mismatches() has ALREADY closed the
underlying stale internal-only signal against real broker-confirmed
evidence (the broker no longer reports that position open) — this is
not a guess or a timeout-based auto-clear, it is recording a real state
change that already happened, with the repair's own signal_ids attached
as evidence. No other control_type is ever auto-resolved, and nothing is
ever auto-waived. Nothing here is ever deleted; resolving/waiving
appends state, it never erases the OPEN row's history (detected_at/
evidence_reference survive unchanged next to the new resolution/waive
fields).

Backed by D1, matching this codebase's own convention for every other
per-tick evidence ledger (execution_attempts, execution_quality,
reconciliation_checks) — a JSONL file (storage/audit_log.py's own
pattern) would make "find the still-open incident with this fingerprint"
an O(n) file scan on every scheduler tick, which D1's indexed query
avoids.
"""
from __future__ import annotations

import json
import uuid
from contextlib import contextmanager
from datetime import datetime, timezone
from typing import Any

from storage import d1_client
from utils.logger import get_logger

logger = get_logger(__name__)

# ── Severity ──────────────────────────────────────────────────────────────
CRITICAL = "CRITICAL"
HIGH = "HIGH"
MEDIUM = "MEDIUM"
LOW = "LOW"
SEVERITIES = (CRITICAL, HIGH, MEDIUM, LOW)

# ── State machine ─────────────────────────────────────────────────────────
OPEN = "OPEN"
ACKNOWLEDGED = "ACKNOWLEDGED"
RESOLVED = "RESOLVED"
WAIVED = "WAIVED"
STATUSES = (OPEN, ACKNOWLEDGED, RESOLVED, WAIVED)
TERMINAL_STATUSES = (RESOLVED, WAIVED)

# ── Control types ────────────────────────────────────────────────────────
# Every type generated by execution/post_trade_monitor.py today, plus 3
# defined-but-not-yet-populated types (see that module's own docstring
# for exactly which ones and why — "do not invent events without
# evidence" applies to control types as much as to individual incidents).
RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
RECONCILIATION_CONTROL_UNAVAILABLE = "RECONCILIATION_CONTROL_UNAVAILABLE"
OUTCOME_RECONCILIATION_GAP = "OUTCOME_RECONCILIATION_GAP"
EXECUTION_TIMEOUT_UNKNOWN = "EXECUTION_TIMEOUT_UNKNOWN"
EXECUTION_REJECTED = "EXECUTION_REJECTED"
FILL_UNAVAILABLE = "FILL_UNAVAILABLE"
POSITION_STATE_MISMATCH = "POSITION_STATE_MISMATCH"  # defined, unused — see post_trade_monitor.py
SLIPPAGE_ANOMALY = "SLIPPAGE_ANOMALY"
LATENCY_ANOMALY = "LATENCY_ANOMALY"
KILL_SWITCH_ACTIVATED = "KILL_SWITCH_ACTIVATED"
KILL_SWITCH_CORRUPTION = "KILL_SWITCH_CORRUPTION"
KILL_SWITCH_STATE_CHANGE = "KILL_SWITCH_STATE_CHANGE"
FORWARD_REVIEW_TRIGGERED = "FORWARD_REVIEW_TRIGGERED"
DATA_PROVENANCE_GAP = "DATA_PROVENANCE_GAP"  # defined, unused — see post_trade_monitor.py
CONTROL_TYPES = (
    RECONCILIATION_MISMATCH, RECONCILIATION_CONTROL_UNAVAILABLE, OUTCOME_RECONCILIATION_GAP,
    EXECUTION_TIMEOUT_UNKNOWN, EXECUTION_REJECTED, FILL_UNAVAILABLE, POSITION_STATE_MISMATCH,
    SLIPPAGE_ANOMALY, LATENCY_ANOMALY, KILL_SWITCH_ACTIVATED, KILL_SWITCH_CORRUPTION,
    KILL_SWITCH_STATE_CHANGE, FORWARD_REVIEW_TRIGGERED, DATA_PROVENANCE_GAP,
)


@contextmanager
def _conn():
    with d1_client.d1_connection() as con:
        yield con


def _init_db() -> None:
    with _conn() as con:
        con.execute("""
        CREATE TABLE IF NOT EXISTS post_trade_incidents (
            incident_id         TEXT PRIMARY KEY,
            fingerprint         TEXT NOT NULL,
            control_type        TEXT NOT NULL,
            severity            TEXT NOT NULL,
            status              TEXT NOT NULL,
            detected_at         TEXT NOT NULL,
            last_seen_at        TEXT NOT NULL,
            symbol              TEXT,
            order_id            TEXT,
            position_id         TEXT,
            signal_id           TEXT,
            expected_state      TEXT,
            actual_state        TEXT,
            source_component    TEXT NOT NULL,
            evidence_reference  TEXT,
            acknowledgement     TEXT,
            acknowledged_by     TEXT,
            acknowledged_at     TEXT,
            resolution          TEXT,
            resolved_by         TEXT,
            resolved_at         TEXT,
            waive_reason        TEXT,
            waived_by           TEXT,
            waived_at           TEXT,
            git_commit          TEXT,
            created_at          TEXT NOT NULL,
            updated_at          TEXT NOT NULL
        )
        """)
        con.execute(
            "CREATE INDEX IF NOT EXISTS idx_pti_fingerprint_status "
            "ON post_trade_incidents(fingerprint, status)"
        )
        con.execute(
            "CREATE INDEX IF NOT EXISTS idx_pti_status_severity "
            "ON post_trade_incidents(status, severity)"
        )
        con.execute(
            "CREATE INDEX IF NOT EXISTS idx_pti_control_type ON post_trade_incidents(control_type)"
        )


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _current_git_commit() -> str | None:
    try:
        from research.manifest import git_state
        return git_state().get("commit")
    except Exception:  # noqa: BLE001 — provenance tagging must never break a write
        return None


def upsert_incident(
    *,
    fingerprint: str,
    control_type: str,
    severity: str,
    source_component: str,
    symbol: str | None = None,
    order_id: str | None = None,
    position_id: str | None = None,
    signal_id: str | None = None,
    expected_state: str | None = None,
    actual_state: str | None = None,
    evidence_reference: dict[str, Any] | None = None,
) -> str:
    """Creates a new OPEN incident, or — if one with this exact
    fingerprint is already OPEN/ACKNOWLEDGED — bumps its last_seen_at
    (and refreshes actual_state/evidence) instead of creating a
    duplicate. Never raises out to the caller: a scan that can't persist
    its finding must not itself become an outage (matches storage/
    execution_attempts.py's own non-raising convention)."""
    if control_type not in CONTROL_TYPES:
        raise ValueError(f"control_type must be one of {CONTROL_TYPES}, got {control_type!r}")
    if severity not in SEVERITIES:
        raise ValueError(f"severity must be one of {SEVERITIES}, got {severity!r}")

    now = _now()
    evidence_json = json.dumps(evidence_reference) if evidence_reference is not None else None
    try:
        _init_db()
        with _conn() as con:
            existing = con.execute(
                "SELECT incident_id FROM post_trade_incidents "
                "WHERE fingerprint=? AND status NOT IN (?,?) "
                "ORDER BY created_at DESC LIMIT 1",
                (fingerprint, RESOLVED, WAIVED),
            ).fetchone()
            if existing:
                incident_id = existing["incident_id"]
                con.execute(
                    "UPDATE post_trade_incidents SET last_seen_at=?, actual_state=?, "
                    "evidence_reference=?, updated_at=? WHERE incident_id=?",
                    (now, actual_state, evidence_json, now, incident_id),
                )
                return incident_id

            incident_id = uuid.uuid4().hex
            con.execute(
                """
                INSERT INTO post_trade_incidents
                (incident_id, fingerprint, control_type, severity, status,
                 detected_at, last_seen_at, symbol, order_id, position_id, signal_id,
                 expected_state, actual_state, source_component, evidence_reference,
                 git_commit, created_at, updated_at)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """,
                (
                    incident_id, fingerprint, control_type, severity, OPEN,
                    now, now, symbol, order_id, position_id, signal_id,
                    expected_state, actual_state, source_component, evidence_json,
                    _current_git_commit(), now, now,
                ),
            )
            return incident_id
    except Exception as exc:  # noqa: BLE001 — monitoring must never itself become an outage
        logger.warning(f"post_trade_incidents: upsert failed for fingerprint={fingerprint!r}: {exc}")
        return ""


def has_terminal_incident(fingerprint: str) -> bool:
    """True if the most recent incident with this fingerprint is already
    RESOLVED/WAIVED. Lets a scan function skip re-flagging an event an
    operator has already dispositioned, for evidence sources with no
    mutable status of their own to check instead — e.g. storage/
    execution_attempts.py's append-only log, where the same historical
    TIMEOUT_UNKNOWN row can still appear inside a later scan's `limit`-
    sized window after its incident was already resolved."""
    _init_db()
    with _conn() as con:
        row = con.execute(
            "SELECT status FROM post_trade_incidents WHERE fingerprint=? "
            "ORDER BY created_at DESC LIMIT 1",
            (fingerprint,),
        ).fetchone()
    return bool(row) and row["status"] in TERMINAL_STATUSES


def get_incident(incident_id: str) -> dict[str, Any] | None:
    _init_db()
    with _conn() as con:
        row = con.execute(
            "SELECT * FROM post_trade_incidents WHERE incident_id=?", (incident_id,)
        ).fetchone()
    return _deserialize(dict(row)) if row else None


def list_incidents(
    status: str | None = None,
    severity: str | None = None,
    control_type: str | None = None,
    limit: int = 200,
) -> list[dict[str, Any]]:
    """Newest-detected first. Optional filters — omit any to see every
    matching row regardless of that dimension."""
    _init_db()
    clauses, params = [], []
    if status is not None:
        clauses.append("status=?")
        params.append(status)
    if severity is not None:
        clauses.append("severity=?")
        params.append(severity)
    if control_type is not None:
        clauses.append("control_type=?")
        params.append(control_type)
    where = f"WHERE {' AND '.join(clauses)}" if clauses else ""
    with _conn() as con:
        rows = con.execute(
            f"SELECT * FROM post_trade_incidents {where} ORDER BY detected_at DESC LIMIT ?",
            (*params, limit),
        ).fetchall()
    return [_deserialize(dict(r)) for r in rows]


def _deserialize(row: dict[str, Any]) -> dict[str, Any]:
    for key in ("evidence_reference", "resolution"):
        raw = row.get(key)
        if raw:
            try:
                row[key] = json.loads(raw)
            except (TypeError, ValueError):
                pass
    return row


def counts_by_status() -> dict[str, int]:
    _init_db()
    with _conn() as con:
        rows = con.execute(
            "SELECT status, COUNT(*) AS n FROM post_trade_incidents GROUP BY status"
        ).fetchall()
    return {r["status"]: r["n"] for r in rows}


def counts_by_severity(status: str | None = None) -> dict[str, int]:
    """Defaults to open (non-terminal) incidents only — a resolved
    CRITICAL from last week shouldn't inflate today's severity summary."""
    _init_db()
    with _conn() as con:
        if status is not None:
            rows = con.execute(
                "SELECT severity, COUNT(*) AS n FROM post_trade_incidents "
                "WHERE status=? GROUP BY severity", (status,),
            ).fetchall()
        else:
            rows = con.execute(
                "SELECT severity, COUNT(*) AS n FROM post_trade_incidents "
                "WHERE status NOT IN (?,?) GROUP BY severity", (RESOLVED, WAIVED),
            ).fetchall()
    return {r["severity"]: r["n"] for r in rows}


def acknowledge_incident(incident_id: str, actor: str, note: str | None = None) -> dict[str, Any]:
    """OPEN -> ACKNOWLEDGED only. Raises ValueError on an unknown
    incident or any other current status — acknowledging is a single,
    explicit step, never a silent no-op on an already-acknowledged or
    already-closed incident (the caller/route must handle that
    explicitly, matching kill_switch's own "already active" 409
    precedent)."""
    incident = get_incident(incident_id)
    if incident is None:
        raise ValueError(f"Unknown incident_id {incident_id!r}")
    if incident["status"] != OPEN:
        raise ValueError(f"Incident {incident_id} is {incident['status']}, not OPEN — cannot acknowledge.")
    now = _now()
    with _conn() as con:
        con.execute(
            "UPDATE post_trade_incidents SET status=?, acknowledgement=?, "
            "acknowledged_by=?, acknowledged_at=?, updated_at=? WHERE incident_id=?",
            (ACKNOWLEDGED, note, actor, now, now, incident_id),
        )
    logger.info(f"post_trade_incidents: {incident_id} ACKNOWLEDGED by {actor}")
    return get_incident(incident_id)  # type: ignore[return-value]


def resolve_incident(
    incident_id: str, actor: str, reason: str, evidence: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """OPEN or ACKNOWLEDGED -> RESOLVED. `reason` is required and must be
    non-blank — resolution always carries evidence of WHY, never a bare
    status flip. Never mutates detected_at/evidence_reference/any other
    historical field — this appends a resolution, it does not rewrite
    the incident's own history. A resolved incident is terminal: calling
    this again (or acknowledge/waive) on it raises."""
    reason = (reason or "").strip()
    if not reason:
        raise ValueError("A resolution must state a reason.")
    incident = get_incident(incident_id)
    if incident is None:
        raise ValueError(f"Unknown incident_id {incident_id!r}")
    if incident["status"] in TERMINAL_STATUSES:
        raise ValueError(f"Incident {incident_id} is already {incident['status']} — cannot resolve again.")
    now = _now()
    resolution_json = json.dumps({"reason": reason, "evidence": evidence})
    with _conn() as con:
        con.execute(
            "UPDATE post_trade_incidents SET status=?, resolution=?, "
            "resolved_by=?, resolved_at=?, updated_at=? WHERE incident_id=?",
            (RESOLVED, resolution_json, actor, now, now, incident_id),
        )
    logger.info(f"post_trade_incidents: {incident_id} RESOLVED by {actor}: {reason}")
    return get_incident(incident_id)  # type: ignore[return-value]


def waive_incident(incident_id: str, actor: str, reason: str) -> dict[str, Any]:
    """OPEN or ACKNOWLEDGED -> WAIVED. `reason` is required and must be
    non-blank. Distinct from resolve_incident: a waiver is an explicit
    operator decision that this incident does not need remediation
    (e.g. a known, already-understood one-off), not proof the underlying
    condition was fixed — kept as its own status/field set so the two
    can never be confused when reviewing history later. Never automatic
    — only ever called from an explicit POST /post-trade/incidents/
    {id}/waive request."""
    reason = (reason or "").strip()
    if not reason:
        raise ValueError("A waiver must state a reason.")
    incident = get_incident(incident_id)
    if incident is None:
        raise ValueError(f"Unknown incident_id {incident_id!r}")
    if incident["status"] in TERMINAL_STATUSES:
        raise ValueError(f"Incident {incident_id} is already {incident['status']} — cannot waive.")
    now = _now()
    with _conn() as con:
        con.execute(
            "UPDATE post_trade_incidents SET status=?, waive_reason=?, "
            "waived_by=?, waived_at=?, updated_at=? WHERE incident_id=?",
            (WAIVED, reason, actor, now, now, incident_id),
        )
    logger.info(f"post_trade_incidents: {incident_id} WAIVED by {actor}: {reason}")
    return get_incident(incident_id)  # type: ignore[return-value]
