"""
utils/provenance.py
--------------------
Decision provenance fingerprints (institutional gap analysis M2 + A3).

Every decision must be attributable to the exact code version, config,
and input data that produced it — otherwise the forward evidence base
cannot *prove* it was generated by an unchanged system, which is what
CLAUDE.md rule 6 ("never change entries/exits/thresholds mid-sample")
requires to be verifiable rather than promised.

Three fingerprints, all cheap, all deterministic:

  git_commit()   — the running code version. Resolved once per process
                   (the deployed tree doesn't change under a running
                   scheduler). Env override IATIS_GIT_COMMIT for
                   containerized deploys without a .git directory.
  config_hash()  — SHA-256 (16 hex chars) over the canonical JSON of the
                   effective config dict. Two runs with identical config
                   hash identically, regardless of dict ordering.
  data_versions()— per timeframe, a structured record of the exact bars
                   the pipeline saw: {provider, first_ts, last_ts,
                   row_count, sha256}. This is what would have made the
                   July 2026 data-starvation incident (614 decisions on
                   a silently truncated window) visible in every stored
                   decision row: row_count=125 instead of ~750.

Would-have-caught check: the philosophy audit reads these back
(scripts/philosophy_audit.py) — a fingerprint change mid-sample without
a registry entry is a live invariant violation.
"""
from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path
from typing import Any

_REPO_ROOT = Path(__file__).resolve().parent.parent

_git_commit_cache: str | None = None


def git_commit() -> str:
    """Short (12-char) commit id of the running tree; cached per process.

    Order: IATIS_GIT_COMMIT env var (containers / no .git) → git
    rev-parse → "unknown". Never raises.
    """
    global _git_commit_cache
    if _git_commit_cache is not None:
        return _git_commit_cache
    env = os.environ.get("IATIS_GIT_COMMIT", "").strip()
    if env:
        _git_commit_cache = env[:40]
        return _git_commit_cache
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"],
            cwd=_REPO_ROOT, capture_output=True, text=True, timeout=5,
        )
        commit = out.stdout.strip()
        _git_commit_cache = commit if out.returncode == 0 and commit else "unknown"
    except Exception:
        _git_commit_cache = "unknown"
    return _git_commit_cache


def config_hash(config: dict) -> str:
    """16-hex-char SHA-256 over the canonical JSON of the config dict.
    `default=str` keeps non-JSON values (Paths, datetimes) hashable and
    deterministic; sort_keys makes dict ordering irrelevant."""
    canonical = json.dumps(config, sort_keys=True, default=str, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


def _frame_sha(df: Any) -> str:
    """Stable 16-hex-char content hash of an OHLCV frame: index + the
    OHLCV columns that exist, rounded to 8 decimals and serialized
    canonically. Same bars → same hash across runs and processes."""
    cols = [c for c in ("open", "high", "low", "close", "volume") if c in df.columns]
    payload = df[cols].round(8).to_csv() if cols else ""
    payload = ",".join(str(i) for i in df.index[:1].tolist() + df.index[-1:].tolist()) + "\n" + payload
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


def data_versions(mtf_data: dict[str, Any] | None) -> dict[str, dict[str, Any]]:
    """Per-timeframe structured data version (addendum A3). Never raises —
    a fingerprinting failure must not block the pipeline; the failing TF
    is recorded as {"error": ...} so the gap itself is auditable."""
    out: dict[str, dict[str, Any]] = {}
    for tf, df in (mtf_data or {}).items():
        try:
            if df is None or len(df) == 0:
                out[tf] = {"provider": None, "row_count": 0}
                continue
            out[tf] = {
                "provider": str(df.attrs.get("provider", "unknown")),
                "first_ts": str(df.index[0]),
                "last_ts": str(df.index[-1]),
                "row_count": int(len(df)),
                "sha256": _frame_sha(df),
            }
        except Exception as exc:  # noqa: BLE001 — never block the pipeline
            out[tf] = {"error": f"{type(exc).__name__}: {exc}"}
    return out


def build_provenance(config: dict, mtf_data: dict[str, Any] | None) -> dict[str, Any]:
    """The complete provenance block attached to every pipeline report."""
    return {
        "git_commit": git_commit(),
        "config_hash": config_hash(config),
        "data_versions": data_versions(mtf_data),
    }
